### ISSUE TITLE
[12.0] doubt about stock_user_default_warehouse_*

### ISSUE THREAD

**Issue by LuqueDaniel** [akretion/odoo-usability#118]
I am migrating a database from Odoo 10.0 to 12.0, that database depends on `stock_user_default_warehouse_*`. Is there an alternative to these addons?

I'm going to start the `stock_user_default_warehouse_*` migration next week in case there isn't an alternative.

**Comment by bealdav** [comment]
Thanks for your contribution.

Could you apply this strategy https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#technical-method-to-migrate-a-module-from-110-to-120-branch to migrate these modules or amend your commit to set original author ? Thanks a lot

**Comment by LuqueDaniel** [comment]
@bealdav Done!

**Comment by bealdav** [comment]
Thanks a lot @LuqueDaniel .
Now you can add your own additional commits at least these :
- move description content from manifest in readme fragments like in OCA : see this module as example https://github.com/akretion/odoo-usability/tree/12.0/account_usability (you have to install https://github.com/OCA/maintainer-tools and operate with https://github.com/OCA/maintainer-tools#readme-generator
- migrate elements which change in v12 like remove class in super: `super(MyClass, self).mymethod() `becomes `super().mymethod() `
- migrate other elements if necessary in the version

Thanks a lot

**Comment by LuqueDaniel** [comment]
@bealdav Done! Thank you for your feedback :)
