### ISSUE TITLE
[14.0] stock_valuation_xlsx : Some references does not exist

### ISSUE THREAD

**Issue by tgaullier** [akretion/odoo-usability#157]
ir.model.access.csv is referenced in the manifest but does not exist.

https://github.com/akretion/odoo-usability/blob/e1a84973da919bb8c80ecc69348777458869af5c/stock_valuation_xlsx/__manifest__.py#L40

**Comment by tgaullier** [comment]
These are the extra references :
security/ir.model.access.csv
wizard/stock_variation_xlsx_view.xml
views/stock_expiry_depreciation_rule.xml

**Comment by bealdav** [comment]
Please could you make a PR if any bug.
Thanks

**Comment by alexis-via** [comment]
Fixed long time ago
