### ISSUE TITLE
[16.0] Switch translate=True to translate=False on char fields

### ISSUE THREAD

**Issue by alexis-via** [akretion/odoo-usability#190]
In our usability modules, we used to switch some char fields from translate=True to Translate=False. For example: https://github.com/akretion/odoo-usability/blob/16.0/base_usability/models/ir_actions_report.py#L15

This is a problem in v16 ; I guess that, when you do that in v16, you have to do a migration script to convert the data from json to char.

Unless if you have a great technical idea, I think I'll remove this kind of change from usability modules (unless if we find an easy solution, I think this change to translate=False may not be worth the technical complexity)

**Comment by PierrickBrun** [comment]
I think a good solution would be to remove them but keep the list of fields in a ROADMAP.rst file

**Comment by florian-dacosta** [comment]
Same as Pierrick, I guess, as it is quite urgent, you can remove it, and we'll put it back later, when we are more used to the translated field in v16.

**Comment by bealdav** [comment]
> you have to do a migration script to convert the data from json to char.

Even If you do that, what happens if you make an `-u all`. Is it cleanly supported ?

I'm ok to remove translate=False to go fast

EDIT : is it possible to make a hack to let jsonb but prevent to have other language than the default one (only one key) ?

**Comment by sebastienbeau** [comment]
Good point.
It's seem that odoo convert the column automatically (I tried to remove translation on product and the data have been migrated).

But, we should take the time to test what is happening when we update the original module


In any case after some testing, it's seem that the new translation implementation fix some issue we have before.

For example, if you have only the french lang activated (most of our customer) then the FR and US translation have always the same value (edit, copy....).

So maybe we will have less issue and so do not need to set translate=False

**Comment by sebastienbeau** [comment]
So let's remove first the transalation=False and see if we still have issue

**Comment by bealdav** [comment]
https://github.com/odoo/odoo/issues/107599

**Comment by alexis-via** [comment]
done
