### ISSUE TITLE
v11 branch?

### ISSUE THREAD

**Issue by ghost** [akretion/odoo-usability#74]
hey there :slightly_smiling_face: 
I was migrating `account_invoice_update_wizard` to 11.0 and even made it to a pull request attempt, but there's no such thing as v11 branch in this repo to contribute into
can you perform an initial setup, please?

**Comment by bealdav** [comment]
Hi @arkostyuk 
Not sure it's a good idea because no one @ akretion have a 11.0 project.

We jump from 10.0 to 12.0 (only one version during two year, policy)

May be you can keep this branch on your repo ?

**Comment by simahawk** [comment]
@bealdav we gonna open our fork for v11, we can live perfectly w/ it :wink: 
Still, would it be a burden to have it here?
You can state is un-maintained by you but at least whoever is looking for v11 things here is going to find something, no?

**Comment by bealdav** [comment]
Done
