### ISSUE TITLE
[12.0] product_usability improvment

### ISSUE THREAD

**Issue by florian-dacosta** [akretion/odoo-usability#90]
Hi @rvalyi @bealdav @alexis-via 
Something that annoys me with recent version it that the default view of product template is the kanban one.
I think it is useless for products, it is slower, etc...
I was about to change the order in a custom module in version 12, to put the tree view by default but I wonder if it could go here.

What do you think?

**Comment by rvalyi** [comment]
I agree with you. So for me +1 to have it in product_usability.

**Comment by rvalyi** [comment]
Well in fact, you can imagine that a small company with 30 products or so (like a service company) prefer the kanban view... So not sure if that can be a property that could be changed back to kanban... or another module like https://github.com/akretion/odoo-usability/tree/12.0/partner_tree_default may be?

**Comment by florian-dacosta** [comment]
Thanks for you opinion.
I think that too much very small module would end never used.
Like all, product usability make choices, the goal is to improve usability for all or 90% of our clients.
For me, the 30 product-s company that would prefer kanban view is the exception.

Let's wait others opinion, if majority is not in favor, I will do a micro module like this one https://github.com/akretion/odoo-usability/tree/12.0/partner_tree_default

**Comment by bealdav** [comment]
+1 for me

**Comment by alexis-via** [comment]
Yes, let's have a module product_tree_default, similar to partner_tree_default !

**Comment by florian-dacosta** [comment]
Well ok, the majority seems in favor to make a separated module, I'll do this.
Thanks all for the fast answer!
